# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83006e97a4937c595f969374b307aa897c62a2c68d0e52e069d3ca7dc672181b597a246a35b8389542b5413117becdf3d02e9d35db6a754fa3c3b583e48c9fcb

test:
  secret_key_base: 2c76f5a8690ea274e3e3d56c81fcc9efa3cb4ab31c53696cf9ad42d6056e793bebe9638cd17d47a3dca078e76d22719be74fdcff47365c7ea2ded93a722b87e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
